version: '3'
services:
  backend:
    image: kanban-backend:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    environment:
      - frontend.url=http://localhost:3000
      - gitlabServer.url=https://gitlab.com
  frontend:
    image: kanban-frontend:latest
    build:
      context: '../A38-Kanban-development-Frontend'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_GITLAB_SERVER=https://gitlab.com
      - REACT_APP_GITLAB_APP_ID=fb5719d5cb6621374b28c03ce5c59cdcc79713b31c636216694dae247787bcf3
      - REACT_APP_GITLAB_APP_SECRET=6456ed6cc7c7be3c9b90e2bf9e6075372dbcd4cfbc980fbc246ebc60b7e6d85f
      - REACT_APP_APPLICATION=http://localhost:3000
    stdin_open: true